// source: onos/config/configuration/network/types.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var gogoproto_gogo_pb = require('../../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var onos_config_configuration_types_pb = require('../types_pb.js');
goog.object.extend(proto, onos_config_configuration_types_pb);
goog.exportSymbol('proto.onos.config.configuration.network.DeviceConfigurationRef', null, global);
goog.exportSymbol('proto.onos.config.configuration.network.NetworkConfiguration', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onos.config.configuration.network.NetworkConfiguration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.onos.config.configuration.network.NetworkConfiguration.repeatedFields_, null);
};
goog.inherits(proto.onos.config.configuration.network.NetworkConfiguration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onos.config.configuration.network.NetworkConfiguration.displayName = 'proto.onos.config.configuration.network.NetworkConfiguration';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onos.config.configuration.network.DeviceConfigurationRef = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onos.config.configuration.network.DeviceConfigurationRef, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onos.config.configuration.network.DeviceConfigurationRef.displayName = 'proto.onos.config.configuration.network.DeviceConfigurationRef';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.onos.config.configuration.network.NetworkConfiguration.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.toObject = function(opt_includeInstance) {
  return proto.onos.config.configuration.network.NetworkConfiguration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onos.config.configuration.network.NetworkConfiguration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onos.config.configuration.network.NetworkConfiguration.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    index: jspb.Message.getFieldWithDefault(msg, 2, 0),
    revision: jspb.Message.getFieldWithDefault(msg, 3, 0),
    status: (f = msg.getStatus()) && onos_config_configuration_types_pb.Status.toObject(includeInstance, f),
    retention: (f = msg.getRetention()) && onos_config_configuration_types_pb.RetentionOptions.toObject(includeInstance, f),
    created: (f = msg.getCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updated: (f = msg.getUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    refsList: jspb.Message.toObjectList(msg.getRefsList(),
    proto.onos.config.configuration.network.DeviceConfigurationRef.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration}
 */
proto.onos.config.configuration.network.NetworkConfiguration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onos.config.configuration.network.NetworkConfiguration;
  return proto.onos.config.configuration.network.NetworkConfiguration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onos.config.configuration.network.NetworkConfiguration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration}
 */
proto.onos.config.configuration.network.NetworkConfiguration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIndex(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRevision(value);
      break;
    case 4:
      var value = new onos_config_configuration_types_pb.Status;
      reader.readMessage(value,onos_config_configuration_types_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 6:
      var value = new onos_config_configuration_types_pb.RetentionOptions;
      reader.readMessage(value,onos_config_configuration_types_pb.RetentionOptions.deserializeBinaryFromReader);
      msg.setRetention(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdated(value);
      break;
    case 10:
      var value = new proto.onos.config.configuration.network.DeviceConfigurationRef;
      reader.readMessage(value,proto.onos.config.configuration.network.DeviceConfigurationRef.deserializeBinaryFromReader);
      msg.addRefs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onos.config.configuration.network.NetworkConfiguration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onos.config.configuration.network.NetworkConfiguration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onos.config.configuration.network.NetworkConfiguration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRevision();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      onos_config_configuration_types_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getRetention();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      onos_config_configuration_types_pb.RetentionOptions.serializeBinaryToWriter
    );
  }
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRefsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.onos.config.configuration.network.DeviceConfigurationRef.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 index = 2;
 * @return {number}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 revision = 3;
 * @return {number}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getRevision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setRevision = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional onos.config.configuration.Status status = 4;
 * @return {?proto.onos.config.configuration.Status}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getStatus = function() {
  return /** @type{?proto.onos.config.configuration.Status} */ (
    jspb.Message.getWrapperField(this, onos_config_configuration_types_pb.Status, 4));
};


/**
 * @param {?proto.onos.config.configuration.Status|undefined} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
*/
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional onos.config.configuration.RetentionOptions retention = 6;
 * @return {?proto.onos.config.configuration.RetentionOptions}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getRetention = function() {
  return /** @type{?proto.onos.config.configuration.RetentionOptions} */ (
    jspb.Message.getWrapperField(this, onos_config_configuration_types_pb.RetentionOptions, 6));
};


/**
 * @param {?proto.onos.config.configuration.RetentionOptions|undefined} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
*/
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setRetention = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.clearRetention = function() {
  return this.setRetention(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.hasRetention = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp created = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
*/
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setCreated = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.clearCreated = function() {
  return this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
*/
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setUpdated = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.clearUpdated = function() {
  return this.setUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.hasUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated DeviceConfigurationRef refs = 10;
 * @return {!Array<!proto.onos.config.configuration.network.DeviceConfigurationRef>}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.getRefsList = function() {
  return /** @type{!Array<!proto.onos.config.configuration.network.DeviceConfigurationRef>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.onos.config.configuration.network.DeviceConfigurationRef, 10));
};


/**
 * @param {!Array<!proto.onos.config.configuration.network.DeviceConfigurationRef>} value
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
*/
proto.onos.config.configuration.network.NetworkConfiguration.prototype.setRefsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.onos.config.configuration.network.DeviceConfigurationRef=} opt_value
 * @param {number=} opt_index
 * @return {!proto.onos.config.configuration.network.DeviceConfigurationRef}
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.addRefs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.onos.config.configuration.network.DeviceConfigurationRef, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.onos.config.configuration.network.NetworkConfiguration} returns this
 */
proto.onos.config.configuration.network.NetworkConfiguration.prototype.clearRefsList = function() {
  return this.setRefsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.prototype.toObject = function(opt_includeInstance) {
  return proto.onos.config.configuration.network.DeviceConfigurationRef.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onos.config.configuration.network.DeviceConfigurationRef} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.toObject = function(includeInstance, msg) {
  var f, obj = {
    deviceConfigurationId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onos.config.configuration.network.DeviceConfigurationRef}
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onos.config.configuration.network.DeviceConfigurationRef;
  return proto.onos.config.configuration.network.DeviceConfigurationRef.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onos.config.configuration.network.DeviceConfigurationRef} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onos.config.configuration.network.DeviceConfigurationRef}
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceConfigurationId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onos.config.configuration.network.DeviceConfigurationRef.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onos.config.configuration.network.DeviceConfigurationRef} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceConfigurationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string device_configuration_id = 1;
 * @return {string}
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.prototype.getDeviceConfigurationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.onos.config.configuration.network.DeviceConfigurationRef} returns this
 */
proto.onos.config.configuration.network.DeviceConfigurationRef.prototype.setDeviceConfigurationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.onos.config.configuration.network);
