// Code generated by GENERATOR. DO NOT EDIT.

import * as jspb from "google-protobuf"

import * as google_protobuf_timestamp_pb from 'google-protobuf/google/protobuf/timestamp_pb';
import * as gogoproto_gogo_pb from '../../../../gogoproto/gogo_pb';
import * as onos_config_configuration_types_pb from '../types_pb';
import * as onos_config_change_device_types_pb from '../../change/device/types_pb';

export class DeviceConfiguration extends jspb.Message {
  getId(): string;
  setId(value: string): void;

  getDeviceId(): string;
  setDeviceId(value: string): void;

  getDeviceVersion(): string;
  setDeviceVersion(value: string): void;

  getDeviceType(): string;
  setDeviceType(value: string): void;

  getRevision(): number;
  setRevision(value: number): void;

  getNetworkConfiguration(): NetworkConfigurationRef | undefined;
  setNetworkConfiguration(value?: NetworkConfigurationRef): void;
  hasNetworkConfiguration(): boolean;
  clearNetworkConfiguration(): void;

  getMaxNetworkChangeIndex(): number;
  setMaxNetworkChangeIndex(value: number): void;

  getStatus(): onos_config_configuration_types_pb.Status | undefined;
  setStatus(value?: onos_config_configuration_types_pb.Status): void;
  hasStatus(): boolean;
  clearStatus(): void;

  getCreated(): google_protobuf_timestamp_pb.Timestamp | undefined;
  setCreated(value?: google_protobuf_timestamp_pb.Timestamp): void;
  hasCreated(): boolean;
  clearCreated(): void;

  getUpdated(): google_protobuf_timestamp_pb.Timestamp | undefined;
  setUpdated(value?: google_protobuf_timestamp_pb.Timestamp): void;
  hasUpdated(): boolean;
  clearUpdated(): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): DeviceConfiguration.AsObject;
  static toObject(includeInstance: boolean, msg: DeviceConfiguration): DeviceConfiguration.AsObject;
  static serializeBinaryToWriter(message: DeviceConfiguration, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): DeviceConfiguration;
  static deserializeBinaryFromReader(message: DeviceConfiguration, reader: jspb.BinaryReader): DeviceConfiguration;
}

export namespace DeviceConfiguration {
  export type AsObject = {
    id: string,
    deviceId: string,
    deviceVersion: string,
    deviceType: string,
    revision: number,
    networkConfiguration?: NetworkConfigurationRef.AsObject,
    maxNetworkChangeIndex: number,
    status?: onos_config_configuration_types_pb.Status.AsObject,
    created?: google_protobuf_timestamp_pb.Timestamp.AsObject,
    updated?: google_protobuf_timestamp_pb.Timestamp.AsObject,
  }
}

export class NetworkConfigurationRef extends jspb.Message {
  getId(): string;
  setId(value: string): void;

  getIndex(): number;
  setIndex(value: number): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): NetworkConfigurationRef.AsObject;
  static toObject(includeInstance: boolean, msg: NetworkConfigurationRef): NetworkConfigurationRef.AsObject;
  static serializeBinaryToWriter(message: NetworkConfigurationRef, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): NetworkConfigurationRef;
  static deserializeBinaryFromReader(message: NetworkConfigurationRef, reader: jspb.BinaryReader): NetworkConfigurationRef;
}

export namespace NetworkConfigurationRef {
  export type AsObject = {
    id: string,
    index: number,
  }
}

export class Configuration extends jspb.Message {
  getId(): string;
  setId(value: string): void;

  getDeviceId(): string;
  setDeviceId(value: string): void;

  getDeviceVersion(): string;
  setDeviceVersion(value: string): void;

  getDeviceType(): string;
  setDeviceType(value: string): void;

  getConfigurationId(): string;
  setConfigurationId(value: string): void;

  getChangeIndex(): number;
  setChangeIndex(value: number): void;

  getValuesList(): Array<onos_config_change_device_types_pb.PathValue>;
  setValuesList(value: Array<onos_config_change_device_types_pb.PathValue>): void;
  clearValuesList(): void;
  addValues(value?: onos_config_change_device_types_pb.PathValue, index?: number): onos_config_change_device_types_pb.PathValue;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): Configuration.AsObject;
  static toObject(includeInstance: boolean, msg: Configuration): Configuration.AsObject;
  static serializeBinaryToWriter(message: Configuration, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): Configuration;
  static deserializeBinaryFromReader(message: Configuration, reader: jspb.BinaryReader): Configuration;
}

export namespace Configuration {
  export type AsObject = {
    id: string,
    deviceId: string,
    deviceVersion: string,
    deviceType: string,
    configurationId: string,
    changeIndex: number,
    valuesList: Array<onos_config_change_device_types_pb.PathValue.AsObject>,
  }
}

